"""Add pagecss column to Blog table.

Revision ID: 497d48fa3c54
Revises: f9370746fed0
Create Date: 2024-12-22 16:01:16.527554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497d48fa3c54'
down_revision = 'f9370746fed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagecss', sa.TEXT(), nullable=True))
        batch_op.alter_column('mediatype',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs_table', schema=None) as batch_op:
        batch_op.alter_column('mediatype',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('pagecss')

    # ### end Alembic commands ###
