"""Image, mediatype

Revision ID: 7c4fca11fbb8
Revises: 497d48fa3c54
Create Date: 2026-06-23 14:25:23.482420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4fca11fbb8'
down_revision = '497d48fa3c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs_table', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('medialink',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('pagecss',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mediatype', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.drop_column('mediatype')

    with op.batch_alter_table('blogs_table', schema=None) as batch_op:
        batch_op.alter_column('pagecss',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('medialink',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('abstract',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
