"""add, usertable

Revision ID: a242bec89040
Revises: 7c4fca11fbb8
Create Date: 2026-06-26 11:02:12.117192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a242bec89040'
down_revision = '7c4fca11fbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.alter_column('mediatype',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images_table', schema=None) as batch_op:
        batch_op.alter_column('mediatype',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('users_table')
    # ### end Alembic commands ###
