"""empty message

Revision ID: f9370746fed0
Revises: 
Create Date: 2024-12-21 17:40:21.020578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9370746fed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('medialink', sa.String(), nullable=False),
    sa.Column('mediatype', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagetitle', sa.String(), nullable=False),
    sa.Column('pageroute', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('refinfo', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('reflink', sa.String(), nullable=False),
    sa.Column('reftype', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagelink', sa.String(), nullable=False),
    sa.Column('imagetitle', sa.String(), nullable=False),
    sa.Column('pagerow', sa.Integer(), nullable=False),
    sa.Column('pagecolumn', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images_table')
    op.drop_table('references_table')
    op.drop_table('pages_table')
    op.drop_table('blogs_table')
    # ### end Alembic commands ###
